name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  project: Karrocon.Messaging.Abstractions/Karrocon.Messaging.Abstractions.csproj

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup nuget
      run: dotnet nuget add source --username karrocon --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/karrocon/index.json"
    - name: Restore dependencies
      run: dotnet restore ${{ env.project }}
    - name: Build
      run: dotnet build ${{ env.project }} --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      if: (success() && (github.head_ref == 'refs/heads/main'))
    - name: Publish
      run: dotnet pack --configuration Release ${{ env.project }}
      if: (success() && (github.ref == 'refs/heads/main'))
    - name: dotnet nuget push
      run: dotnet nuget push ${{ github.workspace }}/*.nupkg --api-key ${{ secrets.NUGET_GITHUB_PAT }} --source "github"
      if: (success() && (github.ref == 'refs/heads/main'))
    - name: dotnet nuget push symbols
      run: dotnet nuget push ${{ github.workspace }}/*.snupkg --api-key ${{ secrets.NUGET_GITHUB_PAT }} --source "github"
      if: (success() && (github.ref == 'refs/heads/main'))
